services:
  api:
    image: golang:alpine
    container_name: "api"
    hostname: "api"
    working_dir: /code
    environment:
      - TG_BOT_TOKEN=7602027535:AAGrPptEC__CbwGqT-6vFpc-SdnEBAAtiSY
    volumes:
      - .:/code
      # - /etc/letsencrypt/live/picovpn.ru/fullchain.pem:/etc/letsencrypt/live/picovpn.ru/fullchain.pem
    # depends_on:
    #   - traefik
    command: go build -o /usr/local/bin/api /code/main.go && api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(api.picovpn.ru)"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encr"
networks:
  default:
    external: true
    name: web